name: Mark stale issues and pull requests

on:
  workflow_run:
    workflows: ["Scala CI"]
    branches: [master]
    types:
      - completed
      - success
    check_run:
      types: [completed]
      conclusion: [success]

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
      - name: Github checkout
        uses: actions/checkout@v2

      - name: Print hello
        run: echo "hello sakshi"